theme: jekyll-theme-minimal
title: Noah's homepage
description: This website was created to learn how to use GitHub pages, neat!/ ![Boise State University logo](https://www.boisestate.edu/wp-content/uploads/2025/12/boisestate-stackedlogo-2color-rgb-scaled.png)
